#!/bin/bash
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
curl "https://app.inspekthor.com/minor/15" &
wait